name: Deploy Backend to Render

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run tests (if available)
      run: npm test --if-present

    - name: Check server startup
      run: timeout 10s npm start || true
      env:
        NODE_ENV: test
        PORT: 5000

  deploy-render:
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/backend'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        
    - name: Wait for deployment
      run: |
        echo "Waiting for Render deployment to complete..."
        sleep 60
        
    - name: Health check
      run: |
        echo "Checking backend health..."
        curl -f https://portfolio-backend.onrender.com/api/health || exit 1
        echo "✅ Backend is healthy!"
        
    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 Backend deployed to Render! API available at https://portfolio-backend.onrender.com'
          })

  notify-success:
    needs: deploy-render
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - name: Notify success
      run: |
        echo "✅ Backend deployment successful!"
        echo "🔗 API at: https://portfolio-backend.onrender.com"
        echo "📊 Health check: https://portfolio-backend.onrender.com/api/health"
